### ISSUE TITLE
Internal ERROR on saving filters configuration 

### ISSUE THREAD

**Issue by Dnhatsave** [IntesysOpenway/openway-tasklist#5]
Hi everyone,
I'm face this error when i try to change the filters on alfresco 6, its seems that Alfresco not able to save the filters configuration in the database / alfresco repository. 

![Screenshot from 2020-06-10 12-34-12](https://user-images.githubusercontent.com/43370602/84245840-f6155200-ab05-11ea-9488-678dfd3f1296.png)

**Log file**
`` `ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-50] Exception from executeScript: 05100008 org.alfresco.service.cmr.repository.ContentIOException: 05101105 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/925652b5-e7ff-4127-8404-a73a82619497
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/6/10/10/27/89fb3bfa-073f-47fe-ad7f-6503aabe6d40.bin, mimetype=text/plain, size=3774, encoding=UTF-8, locale=en]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32
 org.springframework.extensions.webscripts.WebScriptException: 05100008 org.alfresco.service.cmr.repository.ContentIOException: 05101105 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/925652b5-e7ff-4127-8404-a73a82619497
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/6/10/10/27/89fb3bfa-073f-47fe-ad7f-6503aabe6d40.bin, mimetype=text/plain, size=3774, encoding=UTF-8, locale=en]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1124)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.mozilla.javascript.JavaScriptException: JavaException: org.alfresco.service.cmr.repository.ContentIOException: 05101105 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/925652b5-e7ff-4127-8404-a73a82619497
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/6/10/10/27/89fb3bfa-073f-47fe-ad7f-6503aabe6d40.bin, mimetype=text/plain, size=3774, encoding=UTF-8, locale=en]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32 (classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js#37)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8._c_main_1(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js:37)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8._c_script_0(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js:41)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8.exec(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
	at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
	at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
	at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
	at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
	... 41 more
2020-06-10 10:33:02,036  ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-46] Exception from executeScript: 05100009 org.alfresco.service.cmr.repository.ContentIOException: 05101108 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/925652b5-e7ff-4127-8404-a73a82619497
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/6/10/10/33/68366158-c678-4d4e-95ca-ed6ac4f913a1.bin, mimetype=text/plain, size=3776, encoding=UTF-8, locale=en]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32
 org.springframework.extensions.webscripts.WebScriptException: 05100009 org.alfresco.service.cmr.repository.ContentIOException: 05101108 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/925652b5-e7ff-4127-8404-a73a82619497
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/6/10/10/33/68366158-c678-4d4e-95ca-ed6ac4f913a1.bin, mimetype=text/plain, size=3776, encoding=UTF-8, locale=en]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1124)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.mozilla.javascript.JavaScriptException: JavaException: org.alfresco.service.cmr.repository.ContentIOException: 05101108 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/925652b5-e7ff-4127-8404-a73a82619497
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/6/10/10/33/68366158-c678-4d4e-95ca-ed6ac4f913a1.bin, mimetype=text/plain, size=3776, encoding=UTF-8, locale=en]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32 (classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js#37)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8._c_main_1(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js:37)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8._c_script_0(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js:41)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_8.exec(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
	at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
	at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
	at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
	at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
	... 41 more
2020-06-10 10:33:57,203  ERROR [heartbeat.datasender.HBDataSenderServiceImpl] [QuartzScheduler_Worker-1] [HB] Target is unavailable: https://hbrx.alfresco.com
 java.net.SocketException: Network is unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.alfresco.heartbeat.datasender.HBDataSenderServiceImpl.isTargetAvailable(HBDataSenderServiceImpl.java:90)
	at org.alfresco.heartbeat.datasender.HBDataSenderServiceImpl.process(HBDataSenderServiceImpl.java:152)
	at org.alfresco.heartbeat.datasender.HBDataSenderServiceImpl.process(HBDataSenderServiceImpl.java:143)
	at org.alfresco.heartbeat.datasender.internal.schedule.HBDataSenderJob.execute(HBDataSenderJob.java:40)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

`

is this a bug for alfresco 6 ? if yes how can i solve it?
I appreciate any help, thanks

**Comment by luca86r** [comment]
Hi,
we have tested this add-on with Alfresco Community 5.1 and we are also using it in Alfresco Community 5.2. We have never tested it with Alfresco 6 because of the "deprecation" of Alfresco Share.

I do not exclude that this is bug of the add-on with the newer versions of Alfresco.
At the moment we are not interested in supporting Alfresco 6 but, if you are a developer and you would like to contribute, you can suggest us a modification or fork the project.

Thanks for your interest

**Comment by RuudGianesini** [comment]
Hi,
I've released a new version. 
This bug should be fixed.

Bye

**Comment by Dnhatsave** [comment]
Hi @RuudGianesini  im still getting te same error,

```
ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-11] Exception from executeScript: 11220046 org.alfresco.service.cmr.repository.ContentIOException: 11220043 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/76bc3886-90d3-44e1-bae9-832bc3ae7a8a
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/12/22/11/53/375e1e63-d2b0-434a-a447-c256f7091426.bin, mimetype=text/plain, size=135, encoding=UTF-8, locale=en_GB]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32
 org.springframework.extensions.webscripts.WebScriptException: 11220046 org.alfresco.service.cmr.repository.ContentIOException: 11220043 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/76bc3886-90d3-44e1-bae9-832bc3ae7a8a
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/12/22/11/53/375e1e63-d2b0-434a-a447-c256f7091426.bin, mimetype=text/plain, size=135, encoding=UTF-8, locale=en_GB]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1124)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:519)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.mozilla.javascript.JavaScriptException: JavaException: org.alfresco.service.cmr.repository.ContentIOException: 11220043 Failed to set content property on stream closure: 
   node: workspace://SpacesStore/76bc3886-90d3-44e1-bae9-832bc3ae7a8a
   property: {http://www.alfresco.org/model/content/1.0}preferenceValues
   writer: ContentAccessor[ contentUrl=store://2020/12/22/11/53/375e1e63-d2b0-434a-a447-c256f7091426.bin, mimetype=text/plain, size=135, encoding=UTF-8, locale=en_GB]
org.springframework.dao.ConcurrencyFailureException: Failed to update node 32 (classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js#37)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_9._c_main_1(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js:37)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_9.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_9._c_script_0(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js:41)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_9.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_9.call(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_alfresco_repository_preference_preferences_post_json_js_9.exec(classpath*:alfresco/templates/webscripts/org/alfresco/repository/preference/preferences.post.json.js)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
	at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
	at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
	at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
	at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
	... 42 more
```

Have you test it with Alfreso Community 6.1.2_GA ??
